version: '3.8'

services:
  graphql-mcp:
    build: .
    container_name: graphql-mcp-ts
    environment:
      - NODE_ENV=production
      - ENDPOINT=http://localhost:4000/graphql
      - HEADERS={}
      - ALLOW_MUTATIONS=false
      - NAME=mcp-graphql
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # For stdio MCP servers, we don't typically need to expose ports
    # but this is here if you want to add HTTP mode later
    # ports:
    #   - "3000:3000"

  # Example GraphQL API for testing
  # graphql-api:
  #   image: graphql/graphql-playground
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - GRAPHQL_ENDPOINT=http://localhost:4000/graphql
